/**
 *
 * @author os225
 */
public class gameUI extends javax.swing.JFrame {

    /**
     * Creates new form gameUI
     */
    public gameUI() {
        initComponents();
        this.setTitle("MENU: Adina el numero");
        //Colocar en medio de la pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFacil = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        btnDificil = new javax.swing.JButton();
        JLtitulo1 = new javax.swing.JLabel();
        JLtitulo4 = new javax.swing.JLabel();
        JLtitulo5 = new javax.swing.JLabel();
        JLtitulo6 = new javax.swing.JLabel();
        JLtitulo7 = new javax.swing.JLabel();
        imgInterfaz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFacil.setBackground(new java.awt.Color(51, 51, 51));
        btnFacil.setForeground(new java.awt.Color(255, 255, 255));
        btnFacil.setText("Jugar");
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 80, 30));

        btnNormal.setBackground(new java.awt.Color(51, 51, 51));
        btnNormal.setForeground(new java.awt.Color(255, 255, 255));
        btnNormal.setText("Jugar");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });
        getContentPane().add(btnNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 80, 30));

        btnDificil.setBackground(new java.awt.Color(51, 51, 51));
        btnDificil.setForeground(new java.awt.Color(255, 255, 255));
        btnDificil.setText("Jugar");
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });
        getContentPane().add(btnDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 80, 30));

        JLtitulo1.setFont(new java.awt.Font("Sarpanch Black", 1, 36)); // NOI18N
        JLtitulo1.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo1.setText("ADIVINA EL NÚMERO");
        getContentPane().add(JLtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 420, 37));

        JLtitulo4.setFont(new java.awt.Font("Sarpanch Black", 0, 18)); // NOI18N
        JLtitulo4.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo4.setText("Difícil");
        getContentPane().add(JLtitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 60, 37));

        JLtitulo5.setFont(new java.awt.Font("Sarpanch Black", 0, 18)); // NOI18N
        JLtitulo5.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo5.setText("Selecciona un modo para jugar:");
        getContentPane().add(JLtitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 320, 37));

        JLtitulo6.setFont(new java.awt.Font("Sarpanch Black", 0, 18)); // NOI18N
        JLtitulo6.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo6.setText("Fácil");
        getContentPane().add(JLtitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 60, 37));

        JLtitulo7.setFont(new java.awt.Font("Sarpanch Black", 0, 18)); // NOI18N
        JLtitulo7.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo7.setText("Normal");
        getContentPane().add(JLtitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, 37));

        imgInterfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/GUImenu.jpg"))); // NOI18N
        getContentPane().add(imgInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
        this.dispose();
        modoFacil Ventana = new modoFacil();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
       this.dispose();
        modoNormal Ventana = new modoNormal();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
        this.dispose();
        modoDificil Ventana = new modoDificil();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnDificilActionPerformed

    /**
     * @param args the command line arguments
     */ public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLtitulo1;
    private javax.swing.JLabel JLtitulo4;
    private javax.swing.JLabel JLtitulo5;
    private javax.swing.JLabel JLtitulo6;
    private javax.swing.JLabel JLtitulo7;
    private javax.swing.JButton btnDificil;
    private javax.swing.JButton btnFacil;
    private javax.swing.JButton btnNormal;
    private javax.swing.JLabel imgInterfaz;
    // End of variables declaration//GEN-END:variables
}
