import com.formdev.flatlaf.FlatLightLaf;    //iconos modernos
/**
 *
 * @author os225
 */
public class gameUI extends javax.swing.JFrame {

    /**
     * Creates new form gameUI
     */
    public gameUI() {
        initComponents();
        this.setTitle("MENU: Adina el numero");
        //Colocar en medio de la pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFacil = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        btnDificil = new javax.swing.JButton();
        JLtitulo3 = new javax.swing.JLabel();
        JLtitulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFacil.setText("Jugar");
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 510, 80, 30));

        btnNormal.setText("Jugar");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });
        getContentPane().add(btnNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 80, 30));

        btnDificil.setText("Jugar");
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });
        getContentPane().add(btnDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 80, 30));

        JLtitulo3.setFont(new java.awt.Font("Sarpanch Black", 0, 18)); // NOI18N
        JLtitulo3.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo3.setText("Selecciona un modo para jugar:");
        getContentPane().add(JLtitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 320, 37));

        JLtitulo1.setFont(new java.awt.Font("Sarpanch Black", 1, 36)); // NOI18N
        JLtitulo1.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo1.setText("ADIVINA EL NÚMERO");
        getContentPane().add(JLtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 420, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/UI1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
        this.dispose();
        modoFacil Ventana = new modoFacil();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
       this.dispose();
        modoNormal Ventana = new modoNormal();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
        this.dispose();
        modoDificil Ventana = new modoDificil();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnDificilActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {

        // 1. Aplicamos el diseño moderno (FlatLaf) y nadie lo interrumpe
        FlatLightLaf.setup();

        // 2. Abrimos la ventana de tu juego (una sola vez)
        java.awt.EventQueue.invokeLater(() -> {

            new gameUI().setVisible(true);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLtitulo1;
    private javax.swing.JLabel JLtitulo3;
    private javax.swing.JButton btnDificil;
    private javax.swing.JButton btnFacil;
    private javax.swing.JButton btnNormal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
