
public class VentanaGanar extends javax.swing.JFrame {

    private String modoDeJuego;
    public VentanaGanar(int intentos, String Modo) {
        initComponents();
        this.setTitle("Ganaste");
        //Colocar en medio de la pantalla
        this.setLocationRelativeTo(null);
        int intento = intentos + 1;
        numIntentos.setText("" + intento);
        this.modoDeJuego = Modo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numIntentos = new javax.swing.JLabel();
        btnVolverMenu = new javax.swing.JButton();
        btnJugarOtraVez = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numIntentos.setBackground(new java.awt.Color(204, 204, 204));
        numIntentos.setFont(new java.awt.Font("Sarpanch Black", 1, 24)); // NOI18N
        numIntentos.setForeground(new java.awt.Color(255, 255, 255));
        numIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(numIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 70, 50));

        btnVolverMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverMenu.setText("Volver al Menu");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnJugarOtraVez.setBackground(new java.awt.Color(51, 51, 51));
        btnJugarOtraVez.setForeground(new java.awt.Color(255, 255, 255));
        btnJugarOtraVez.setText("Volver a jugar");
        btnJugarOtraVez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarOtraVezActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugarOtraVez, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 110, -1));

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ganaste.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnJugarOtraVezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarOtraVezActionPerformed
        this.dispose();
        switch (modoDeJuego) {
            case "Facil":
                modoFacil Ventana1 = new modoFacil();
                Ventana1.setVisible(true);
                break;
            case "Normal":
                modoNormal Ventana2 = new modoNormal();
                Ventana2.setVisible(true);
                break;
            case "Dificil":
                modoDificil Ventana3 = new modoDificil();
                Ventana3.setVisible(true);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnJugarOtraVezActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        this.dispose();
        gameUI Ventana = new gameUI();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnVolverMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugarOtraVez;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numIntentos;
    // End of variables declaration//GEN-END:variables
}
