/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//holaaa
/**
 *
 * @author os225
 */
public class VentanaGanar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGanar
     */
    public VentanaGanar(int intentos) {
        initComponents();
            this.setTitle("Ganaste");
        //Colocar en medio de la pantalla
            this.setLocationRelativeTo(null);
            int intento=intentos+1;
             numIntentos.setText("" + intento );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numIntentos = new javax.swing.JLabel();
        btnRegresarMenu = new javax.swing.JButton();
        btnVjugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numIntentos.setBackground(new java.awt.Color(204, 204, 204));
        numIntentos.setFont(new java.awt.Font("Sarpanch Black", 1, 24)); // NOI18N
        numIntentos.setForeground(new java.awt.Color(255, 255, 255));
        numIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(numIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, 50));

        btnRegresarMenu.setText("Volver al Menu");
        btnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnVjugar.setText("Volver a jugar");
        btnVjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVjugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVjugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ganaste.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVjugarActionPerformed
       this.dispose();
        modoNormal Ventana = new modoNormal();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnVjugarActionPerformed

    private void btnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuActionPerformed
          this.dispose();
        gameUI Ventana = new gameUI();
        Ventana.setVisible(true);
    }//GEN-LAST:event_btnRegresarMenuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVjugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numIntentos;
    // End of variables declaration//GEN-END:variables
}
