/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author os225
 */
public class VentanPerder extends javax.swing.JFrame {

    /**
     * Creates new form UiLost
     */
     private String modoDeJuego;
    public VentanPerder(String numeroObj,String Modo) {
         initComponents();
            this.setTitle("Vuelve a intentarlo");
        //Colocar en medio de la pantalla
            this.setLocationRelativeTo(null);
            
             numeroObjetivo.setText("" + numeroObj );
        this.modoDeJuego = Modo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        numeroObjetivo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        vIntentar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver al Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 110, -1));

        numeroObjetivo.setBackground(new java.awt.Color(204, 204, 204));
        numeroObjetivo.setFont(new java.awt.Font("Sarpanch Black", 1, 36)); // NOI18N
        numeroObjetivo.setForeground(new java.awt.Color(255, 255, 255));
        numeroObjetivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(numeroObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, 50));

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 70, -1));

        vIntentar.setBackground(new java.awt.Color(51, 51, 51));
        vIntentar.setForeground(new java.awt.Color(255, 255, 255));
        vIntentar.setText("Volver a jugar");
        vIntentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vIntentarActionPerformed(evt);
            }
        });
        jPanel1.add(vIntentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/perdiste.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vIntentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vIntentarActionPerformed
         
        this.dispose();
         switch (modoDeJuego) {
            case "Facil":
                 modoFacil Ventana1 = new modoFacil();
                 Ventana1.setVisible(true);
                break;
            case "Normal":
                 modoNormal Ventana2 = new modoNormal();
                 Ventana2.setVisible(true);
                break;
            case "Dificil":
                 modoDificil Ventana3 = new modoDificil();
                 Ventana3.setVisible(true);
                break;
            default:
                throw new AssertionError();
        }
        
    }//GEN-LAST:event_vIntentarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        gameUI Ventana = new gameUI();
        Ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numeroObjetivo;
    private javax.swing.JButton vIntentar;
    // End of variables declaration//GEN-END:variables
}
