/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author os225
 */
public class VentanPerder extends javax.swing.JFrame {

    /**
     * Creates new form UiLost
     */
    public VentanPerder(String numeroObj) {
         initComponents();
            this.setTitle("Vuelve a intentarlo");
        //Colocar en medio de la pantalla
            this.setLocationRelativeTo(null);
            
             numeroObjetivo.setText("" + numeroObj );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numeroObjetivo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        vIntentar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numeroObjetivo.setBackground(new java.awt.Color(204, 204, 204));
        numeroObjetivo.setFont(new java.awt.Font("Sarpanch Black", 1, 36)); // NOI18N
        numeroObjetivo.setForeground(new java.awt.Color(255, 255, 255));
        numeroObjetivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(numeroObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, 50));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 70, -1));

        vIntentar.setText("Volver a jugar");
        vIntentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vIntentarActionPerformed(evt);
            }
        });
        jPanel1.add(vIntentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vIntentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vIntentarActionPerformed
         
        this.dispose();
        modoNormal Ventana = new modoNormal();
        Ventana.setVisible(true);
        
    }//GEN-LAST:event_vIntentarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numeroObjetivo;
    private javax.swing.JButton vIntentar;
    // End of variables declaration//GEN-END:variables
}
